### PR TITLE
Fix pass arg reg

### LINKED ISSUE #570: Run and pass add1.js
After pass add.js and hello.js, we can try this one:

```
function test(v2) {
return v2+66;
}
%PrepareFunctionForOptimization(test);
test(55);
%OptimizeFunctionOnNextCall(test);
test(77);
%DebugPrint(test);
%PrepareFunctionForOptimization(test);
test(55.1);
%OptimizeFunctionOnNextCall(test);
test(77.2);
%DebugPrint(test);
```

### PR DESCRIPTION
**Pull request by luyahan**
Fix #570 
After this pr ,  will occurs error 
```
malloc(): unsorted double linked list corrupted
Received signal 6

==== C stack trace ===============================
```

### CODE REVIEW

File: src/builtins/riscv32/builtins-riscv32.cc [hunk 1]
```diff
@@ -3458,10 +3458,10 @@ void Generate_DeoptimizationEntry(MacroAssembler* masm,
   // Get the address of the location in the code object (a3) (return
```
Comment (qjivy) [inline src/builtins/riscv32/builtins-riscv32.cc]: Should modify this comment too.

**Review by qjivy — CHANGES_REQUESTED** [review]

File: src/builtins/riscv32/builtins-riscv32.cc (hunk 1 above)
Comment (luyahan) [reply src/builtins/riscv32/builtins-riscv32.cc]: done

**Review by qjivy — APPROVED** [review]
